// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSB5UZw8oU_mMeiCbgxyF0oeyG5Pl1Wao',
    appId: '1:457502558799:web:ebf9b90ab1050f4f3ef83a',
    messagingSenderId: '457502558799',
    projectId: 'fir-21312011',
    authDomain: 'fir-21312011.firebaseapp.com',
    storageBucket: 'fir-21312011.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTCxUf4wvzmLWx7zlgDImrWFAMJEghT08',
    appId: '1:457502558799:android:e502b465e2935a253ef83a',
    messagingSenderId: '457502558799',
    projectId: 'fir-21312011',
    storageBucket: 'fir-21312011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQ5Ld0cRP6E670cr9o8FGeBC8aVrddkU',
    appId: '1:457502558799:ios:929a90ff8b56ceec3ef83a',
    messagingSenderId: '457502558799',
    projectId: 'fir-21312011',
    storageBucket: 'fir-21312011.appspot.com',
    iosClientId: '457502558799-gpn8v456o994adf2o8b6jla41381oq4j.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeQ5Ld0cRP6E670cr9o8FGeBC8aVrddkU',
    appId: '1:457502558799:ios:929a90ff8b56ceec3ef83a',
    messagingSenderId: '457502558799',
    projectId: 'fir-21312011',
    storageBucket: 'fir-21312011.appspot.com',
    iosClientId: '457502558799-gpn8v456o994adf2o8b6jla41381oq4j.apps.googleusercontent.com',
    iosBundleId: 'com.ifgabsp.projectGet',
  );
}
